// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsaoLLYpSdkeko1Xis9zrHvVzN0Do2rOc',
    appId: '1:732613622430:web:48c244abff5a8cdce0198f',
    messagingSenderId: '732613622430',
    projectId: 'budcut-308d9',
    authDomain: 'budcut-308d9.firebaseapp.com',
    databaseURL: 'https://budcut-308d9-default-rtdb.firebaseio.com',
    storageBucket: 'budcut-308d9.firebasestorage.app',
    measurementId: 'G-890VVJHGM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2sMA-HRgiKvAknhKeRmXWWf719ZUqr6E',
    appId: '1:732613622430:android:17d974dc6bec3e86e0198f',
    messagingSenderId: '732613622430',
    projectId: 'budcut-308d9',
    databaseURL: 'https://budcut-308d9-default-rtdb.firebaseio.com',
    storageBucket: 'budcut-308d9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnKxZSIEGH_tU_jtRvcD6H0WvPL4Tbz84',
    appId: '1:732613622430:ios:45ab64d89cf24533e0198f',
    messagingSenderId: '732613622430',
    projectId: 'budcut-308d9',
    databaseURL: 'https://budcut-308d9-default-rtdb.firebaseio.com',
    storageBucket: 'budcut-308d9.firebasestorage.app',
    iosBundleId: 'com.example.budcut',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnKxZSIEGH_tU_jtRvcD6H0WvPL4Tbz84',
    appId: '1:732613622430:ios:45ab64d89cf24533e0198f',
    messagingSenderId: '732613622430',
    projectId: 'budcut-308d9',
    databaseURL: 'https://budcut-308d9-default-rtdb.firebaseio.com',
    storageBucket: 'budcut-308d9.firebasestorage.app',
    iosBundleId: 'com.example.budcut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsaoLLYpSdkeko1Xis9zrHvVzN0Do2rOc',
    appId: '1:732613622430:web:c6de2ce6556b6d68e0198f',
    messagingSenderId: '732613622430',
    projectId: 'budcut-308d9',
    authDomain: 'budcut-308d9.firebaseapp.com',
    databaseURL: 'https://budcut-308d9-default-rtdb.firebaseio.com',
    storageBucket: 'budcut-308d9.firebasestorage.app',
    measurementId: 'G-FB8TT7VM19',
  );
}
