name: budcut
description: "Personal Budget & Expense Tracker"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  shared_preferences: ^2.3.4
  intl: ^0.19.0
  csv: ^6.0.0
  uuid: ^4.5.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/B.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/B.png"
  web:
    generate: true
    image_path: "assets/B.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
